server:
  port: 8080

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
  timelimiter:
    instances:
      productService:
        timeoutDuration: 1s
        cancelRunningFuture: true
